# MANDATORY
# The name of the mod loader type to load - for regular FML @Mod mods it should be javafml
modLoader="javafml"
# A version range to match for said mod loader - for regular FML @Mod it will be the forge version
loaderVersion="[31,)"

# A list of mods - how many allowed here is determined by the individual mod loader
[[mods]]
    # The modid of the mod
    modId="shrouds"
    # The version number of the mod
    version="${file.jarVersion}"
    # A display name for the mod
    displayName="Shrouds"
    # The description text for the mod (multi line!)
    description='''
    Adds a beacon-like block whose effects only target hostile mobs'''
    # OPTIONAL
    # A text field displayed in the mod UI
    authors="Aurilux"
    # A text field displayed in the mod UI
    #credits="Thanks for this example mod goes to Java"
    # A file name (in the root of the mod JAR) containing a logo for display
    logoFile="shrouds_logo.png"
    # A URL for the "homepage" for this mod, displayed in the mod UI
    displayURL="https://minecraft.curseforge.com/projects/shrouds"
    # A URL to refer people to when problems occur with this mod
    issueTrackerURL="https://github.com/Aurilux/Shrouds/issues"
    # A URL to query for updates for this mod
    updateJSONURL="https://raw.githubusercontent.com/Aurilux/Shrouds/master/update.json"

# A dependency - use the . to indicate dependency for a specific modid. Dependencies are optional.
[[dependencies.shrouds]]
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[31,)" #mandatory
    # An ordering relationship for the dependency - BEFORE or AFTER required if the relationship is not mandatory
    ordering="NONE"
    # Side this dependency is applied on - BOTH, CLIENT or SERVER
    side="BOTH"